-- 12 · 執事會：簽到 + 會議記錄 + 待辦追蹤
--
-- 執事會沿用 activities（才能直接用現成的 QR 報到與 attendance 出席統計），
-- 但它是內部會議，不該出現在官網與行事曆，未登入者也不該讀得到。

alter table public.activities
  add column if not exists is_internal boolean not null default false;

-- 保險起見用 trigger 釘死：不管從哪條路徑建立，執事會一律是內部活動。
-- 只靠前端記得帶 is_internal 的話，哪天漏掉就是把開會時間地點公開出去。
create or replace function public.force_internal_activity_types()
 returns trigger
 language plpgsql
 set search_path to 'public'
as $function$
begin
  if new.type = '執事會' then
    new.is_internal := true;
  end if;
  return new;
end;
$function$;

drop trigger if exists activities_force_internal on public.activities;
create trigger activities_force_internal
  before insert or update on public.activities
  for each row execute function public.force_internal_activity_types();

-- 未登入者讀不到內部活動（公開頁、行事曆、OG 預覽都靠這條擋）
drop policy if exists activities_public_read on public.activities;
create policy activities_public_read on public.activities
  as permissive for select to anon
  using (coalesce(is_internal, false) = false);

-- 會議記錄：一場會議一份。刪掉會議時記錄與待辦一起走（cascade）
create table if not exists public.meeting_minutes (
  id bigint generated by default as identity primary key,
  activity_id bigint not null unique references public.activities(id) on delete cascade,
  content text,            -- 討論事項
  decisions text,          -- 決議
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.meeting_action_items (
  id bigint generated by default as identity primary key,
  minutes_id bigint not null references public.meeting_minutes(id) on delete cascade,
  content text not null,
  -- 負責人：是會員就連 member_id，不是（例如外部廠商）就只留名字
  owner_member_id bigint references public.members(id) on delete set null,
  owner_name text,
  due_date date,
  status text default 'pending' not null,
  done_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint meeting_action_items_status_valid check (status = any (array['pending'::text, 'done'::text]))
);

create index if not exists meeting_action_items_minutes_idx on public.meeting_action_items (minutes_id);
create index if not exists meeting_action_items_pending_idx on public.meeting_action_items (status, due_date) where status = 'pending';

drop trigger if exists meeting_minutes_set_updated_at on public.meeting_minutes;
create trigger meeting_minutes_set_updated_at before update on public.meeting_minutes
  for each row execute function public.touch_updated_at();
drop trigger if exists meeting_action_items_set_updated_at on public.meeting_action_items;
create trigger meeting_action_items_set_updated_at before update on public.meeting_action_items
  for each row execute function public.touch_updated_at();

alter table public.meeting_minutes enable row level security;
alter table public.meeting_action_items enable row level security;

create policy meeting_minutes_admin_read on public.meeting_minutes
  as permissive for select to authenticated using (is_changzhan_admin());
create policy meeting_minutes_editor_write on public.meeting_minutes
  as permissive for all to authenticated
  using (is_changzhan_editor()) with check (is_changzhan_editor());

create policy meeting_action_items_admin_read on public.meeting_action_items
  as permissive for select to authenticated using (is_changzhan_admin());
create policy meeting_action_items_editor_write on public.meeting_action_items
  as permissive for all to authenticated
  using (is_changzhan_editor()) with check (is_changzhan_editor());
