-- 01 · 資料表
--
-- 由正式環境（qxoglhkfxxqsjefynzqn）反向匯出，2026-09-20。
-- 這是「從零開一套新分會系統」的第一步，跑完這個資料夾裡的 01→05 就會長出完整結構。
--
-- ⚠️ 不含 bni-report 獨佔的表（palms_imports / traffic_light_imports / member_groups）
--    與兩系統共用的 user_roles。新分會如果不跑 bni-report，就不需要它們。

-- signup_sheets.token 的預設值用到 pgcrypto 的 gen_random_bytes()。
-- Supabase 把擴充套件裝在 extensions schema，不在預設 search_path 裡，
-- 所以要明確指定 schema，否則在乾淨的新專案上會噴
-- 「function gen_random_bytes(integer) does not exist」。
create extension if not exists pgcrypto with schema extensions;

-- 早期用 serial 建的表，預設值是 nextval()，所以序列要先存在
create sequence if not exists public.documents_id_seq;
create sequence if not exists public.guests_id_seq;
create sequence if not exists public.message_send_log_id_seq;
create sequence if not exists public.milestones_id_seq;

create table if not exists public.activities (
  id bigint generated by default as identity not null,
  title text,
  date date,
  price integer,
  description text,
  created_at timestamp with time zone default now() not null,
  location text,
  type text,
  "time" text,
  picture text,
  status text default 'active'::text,
  checkin_token text,
  checkin_token_expires_at timestamp with time zone,
  guest_welcome_message text,
  member_price integer
);

create table if not exists public.admins (
  id uuid default gen_random_uuid() not null,
  name text,
  role text,
  created_at timestamp with time zone default now() not null,
  password text,
  phone text,
  email text,
  can_edit boolean default true not null
);

create table if not exists public.app_settings (
  key text not null,
  value text,
  description text,
  updated_at timestamp with time zone default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity not null,
  activity_id text not null,
  member_id text not null,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.documents (
  id bigint default nextval('public.documents_id_seq'::regclass) not null,
  title text not null,
  description text,
  category text not null,
  file_name text not null,
  file_path text not null,
  file_url text not null,
  file_size bigint default 0,
  file_type text,
  uploaded_by text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.email_send_log (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  kind text default 'registration_confirmation'::text not null,
  registration_id bigint,
  to_email text not null,
  subject text,
  status text not null,
  provider_id text,
  error_message text
);

create table if not exists public.finance_records (
  id bigint generated by default as identity not null,
  type text not null,
  category text not null,
  amount numeric not null,
  date date not null,
  description text,
  activity_id bigint,
  created_at timestamp with time zone default now(),
  payment_batch_id bigint
);

create table if not exists public.guests (
  id bigint default nextval('public.guests_id_seq'::regclass) not null,
  created_at timestamp with time zone default now() not null,
  line_user_id text not null,
  name text not null,
  phone text not null,
  email text,
  company text,
  notes text
);

create table if not exists public.line_groups (
  id bigint generated by default as identity not null,
  line_group_id text not null,
  name text,
  description text,
  is_active boolean default true not null,
  joined_at timestamp with time zone default now() not null,
  left_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.member_aliases (
  alias_name text not null,
  member_id bigint not null,
  note text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  member_no integer,
  industry_chain text,
  industry_category text,
  name text,
  company text,
  website text,
  intro text,
  status text default 'active'::text,
  join_date text,
  end_date text,
  birthday text,
  picture text,
  company_title text,
  tax_id text,
  mobile_phone text,
  landline text,
  address text,
  group_name text,
  line_user_id text,
  email text
);

create table if not exists public.message_send_log (
  id bigint default nextval('public.message_send_log_id_seq'::regclass) not null,
  created_at timestamp with time zone default now() not null,
  recipient_kind text not null,
  recipient_id bigint not null,
  line_user_id text not null,
  message_text text not null,
  message_hash text not null,
  status text not null,
  error_message text,
  sent_by text,
  batch_id text
);

create table if not exists public.milestones (
  id bigint default nextval('public.milestones_id_seq'::regclass) not null,
  type text not null,
  title text not null,
  date date not null,
  image_url text,
  description text,
  created_at timestamp with time zone default now(),
  images jsonb default '[]'::jsonb
);

create table if not exists public.payable_records (
  id bigint generated by default as identity not null,
  title text not null,
  category text default '其他'::text not null,
  amount integer not null,
  due_date date,
  status text default 'pending'::text not null,
  note text,
  activity_id bigint,
  finance_record_id bigint,
  paid_at timestamp with time zone,
  paid_by text,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.payment_batches (
  id bigint generated by default as identity not null,
  title text not null,
  default_amount integer default 0 not null,
  period text,
  activity_id bigint,
  due_date date,
  finance_category text default '會費'::text not null,
  status text default 'open'::text not null,
  note text,
  created_by text,
  created_at timestamp with time zone default now() not null,
  member_amount integer
);

create table if not exists public.payment_items (
  id bigint generated by default as identity not null,
  batch_id bigint not null,
  payee_name text not null,
  payee_phone text,
  member_id bigint,
  guest_id bigint,
  registration_id bigint,
  amount_due integer default 0 not null,
  amount_paid integer default 0 not null,
  method text,
  paid_at timestamp with time zone,
  note text,
  recorded_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.registrations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  name text,
  phone text,
  email text not null,
  company text,
  title text,
  referrer text,
  "activityId" bigint,
  check_in_status boolean default false,
  paid_amount integer default 0,
  guest_id bigint,
  notes text
);

create table if not exists public.signup_entries (
  id bigint generated by default as identity not null,
  sheet_id bigint not null,
  line_user_id text,
  member_id bigint,
  display_name text,
  real_name text not null,
  phone text,
  company text,
  referrer text,
  extra_count integer default 0 not null,
  extra_names text,
  note text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.signup_sheets (
  id bigint generated by default as identity not null,
  -- 公開連結用隨機 token，不用流水號 id（不然網址數字加一就能看到別人的接龍）。
  -- URL-safe base64：一般 base64 的 '+' 在 query string 會被解成空白。
  token text default translate(encode(extensions.gen_random_bytes(9), 'base64'::text), '+/'::text, '-_'::text) not null,
  title text not null,
  description text,
  activity_id bigint,
  deadline timestamp with time zone,
  max_people integer,
  allow_guests boolean default true not null,
  allow_non_members boolean default true not null,
  status text default 'open'::text not null,
  created_by text,
  created_at timestamp with time zone default now() not null,
  fee integer default 0 not null,
  member_fee integer
);

-- 序列的擁有者接回欄位，日後 drop table 時序列才會一起消失
alter sequence public.documents_id_seq owned by public.documents.id;
alter sequence public.guests_id_seq owned by public.guests.id;
alter sequence public.message_send_log_id_seq owned by public.message_send_log.id;
alter sequence public.milestones_id_seq owned by public.milestones.id;
