-- 14 · 通知發送紀錄（Telegram）
--
-- 報名通知從 LINE 群組改送 Telegram：LINE 的推播有則數限制，
-- 「通知幹部有人報名」這種訊息不值得用掉額度；Telegram Bot API 沒有這個限制。
--
-- 不塞進 message_send_log：那張表的欄位是為 LINE 設計的
-- （recipient_kind 只允許 member/guest/group、line_user_id 是 not null），
-- 硬塞會讓後台的「LINE 發送紀錄」混進不是 LINE 的東西。
create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  channel text not null,              -- telegram / line / ...
  target text,                        -- chat id、群組 id
  message_text text,
  status text not null,               -- sent / failed / skipped
  error_message text,
  ref text,                           -- 例如 reg_123，方便回頭查是哪一筆報名
  created_at timestamp with time zone default now() not null,
  constraint notification_log_status_valid
    check (status = any (array['sent'::text, 'failed'::text, 'skipped'::text]))
);

create index if not exists notification_log_created_idx on public.notification_log (created_at desc);

alter table public.notification_log enable row level security;

-- 只有後台人員讀得到；寫入一律由 edge function 以 service role 進行
create policy notification_log_admin_read on public.notification_log
  as permissive for select to authenticated using (is_changzhan_admin());
