-- 13 · 執事會議程（8 段）＋ 來賓追蹤 ＋ 續約追蹤
--
-- 議程照分會既有簡報：出缺席報告／今日來賓／入會申請／上週來賓／之前來賓／
-- 363 續約／流程優化／臨時動議。能自動算的就不手填。

alter table public.meeting_minutes
  drop column if exists content,
  drop column if exists decisions,
  -- 出缺席報告與來賓分組都要對應到「哪一場例會」
  add column if not exists regular_meeting_activity_id bigint references public.activities(id) on delete set null,
  add column if not exists attendance_note text,
  add column if not exists application_note text,
  add column if not exists guest_note text,
  add column if not exists renewal_note text,
  add column if not exists process_note text,
  add column if not exists misc_note text;

-- 來賓追蹤：一位來賓一筆，狀況跨週延續。
-- 議程的「今日／上週／之前來賓」不是三份資料，而是同一份依 visit_date 分組。
create table if not exists public.guest_follow_ups (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  industry text,
  group_name text,
  member_name text,
  interviewer text,
  status_note text,
  visit_date date,
  state text not null default 'tracking',
  registration_id bigint references public.registrations(id) on delete set null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint guest_follow_ups_state_valid
    check (state = any (array['tracking'::text, 'applied'::text, 'joined'::text, 'dropped'::text]))
);
create index if not exists guest_follow_ups_visit_idx on public.guest_follow_ups (visit_date desc);
create index if not exists guest_follow_ups_state_idx on public.guest_follow_ups (state);

-- 363 續約追蹤：一位會員一筆，滾動更新。到期日與組別讀 members。
create table if not exists public.renewal_notes (
  member_id bigint primary key references public.members(id) on delete cascade,
  status_note text,
  light integer,
  committee text,
  guest_count integer,
  updated_at timestamp with time zone default now() not null
);

drop trigger if exists guest_follow_ups_set_updated_at on public.guest_follow_ups;
create trigger guest_follow_ups_set_updated_at before update on public.guest_follow_ups
  for each row execute function public.touch_updated_at();
drop trigger if exists renewal_notes_set_updated_at on public.renewal_notes;
create trigger renewal_notes_set_updated_at before update on public.renewal_notes
  for each row execute function public.touch_updated_at();

alter table public.guest_follow_ups enable row level security;
alter table public.renewal_notes enable row level security;

create policy guest_follow_ups_admin_read on public.guest_follow_ups
  as permissive for select to authenticated using (is_changzhan_admin());
create policy guest_follow_ups_editor_write on public.guest_follow_ups
  as permissive for all to authenticated
  using (is_changzhan_editor()) with check (is_changzhan_editor());

create policy renewal_notes_admin_read on public.renewal_notes
  as permissive for select to authenticated using (is_changzhan_admin());
create policy renewal_notes_editor_write on public.renewal_notes
  as permissive for all to authenticated
  using (is_changzhan_editor()) with check (is_changzhan_editor());
